version: "2.2"

services:
  app:
    build: ./app
    links:
      - db
      - phpmyadmin
    ports:
      - 8830:5000 #8830 - localhost del host, 5000 del container
  app2:
    build: ./app
    links:
      - db
      - phpmyadmin
    ports:
      - 8831:5000 #8831 - localhost del host, 5000 del container

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USERNAME: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
      - mysql-data:/var/lib/mysql



  phpmyadmin:
      image: phpmyadmin/phpmyadmin:latest
      container_name: phpmyadmin
      restart: always
      links:
        - db
      environment:
        PMA_HOST: db
        PMA_PORT: 3306
        PMA_ARBITRARY: 1
        MYSQL_USERNAME: root
        MYSQL_ROOT_PASSWORD: password
      ports:
        - 8080:80
  

volumes:
  mysql-data:

